### ISSUE TITLE
Manage contact list

### ISSUE THREAD

**Issue by elric72** [tellform/tellform#201] opened 2017-07-17 06:55 UTC
#### About the Feature

Is it plan to manage contact list to send forms to user and manage who fill the forms ?

**Comment by whitef0x0** [comment] 2017-07-21 01:00
@elric72 I'm pretty busy right now but if this is something you're interested in seeing I always appreciate PRs :)

**Comment by whitef0x0** [comment] 2017-11-06 22:18
This is a duplicate of https://github.com/tellform/tellform/issues/223 and will therefore be closed.

**Closed by whitef0x0** 2017-11-06 22:18 UTC
